name: airflow-ect
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - airflow
  - cartopy
  - cftime
  - dask
  - geopandas
  - matplotlib-base
  - numcodecs
  - numpy
  - pandas
  - pip
  - pyproj
  - python-dateutil
  - shapely
  - six
  - xarray
  - xcube >= 1.8.0
  - xcube-cci >= 0.11.1
  - zarr <3  # until we can ensure zarr 3 compatibility
  - pip
  - pip:
      - apache-airflow-providers-docker
      - apache-airflow-providers-cncf-kubernetes
  # Test libs
  - pytest
  - pytest-cov
